"""HTTP-backed implementation of the Claude Chat API contract.

This adapter uses the autogenerated `claude_chat_service_client` to call the
running FastAPI service over HTTP and exposes the `AbstractClaudeChatAPI`
interface defined by `claude_chat_api`.
"""

from .service_adapter import ServiceClaudeChat

__all__ = ["ServiceClaudeChat"]

