"""Service-backed implementation of the AI chat API contract.

This adapter wraps the autogenerated HTTP client (generated from the
ai_chat_service OpenAPI spec) and exposes the `ai_chat_api.Client`
interface so callers can remain unaware of network concerns.
"""

from __future__ import annotations

import httpx

from ai_chat_api import Client, Message

try:
    # These imports rely on running openapi-python-client to generate the client first
    # Path: src/claude_chat_service_client/fast_api_client
    from claude_chat_service_client.client import Client as GeneratedClient

    try:
        # If an operation function exists for POST /chat, we'll try to import it dynamically.
        # Otherwise, we'll fall back to using the low-level httpx Client from the generated Client.
        from importlib import import_module

        _OP_MODULE = None
        _OP_FUNC = None
        try:
            # Common location based on tag folder ("chat") and operationId naming
            _OP_MODULE = import_module("claude_chat_service_client.api.chat.send_chat_message_chat_post")
            _OP_FUNC = getattr(_OP_MODULE, "sync", None)  # type: ignore[attr-defined]
            from claude_chat_service_client.models.chat_request import ChatRequest as _GenChatRequest  # type: ignore[no-redef]
        except Exception:
            _OP_MODULE = None
            _OP_FUNC = None
            _GenChatRequest = None  # type: ignore[assignment]
    except Exception:  # pragma: no cover - optional dynamic import path
        GeneratedClient = None  # type: ignore[assignment]
        _OP_FUNC = None
        _GenChatRequest = None  # type: ignore[assignment]
except Exception:  # pragma: no cover - generated client absent
    GeneratedClient = None  # type: ignore[assignment]
    _OP_FUNC = None
    _GenChatRequest = None  # type: ignore[assignment]


class _AdapterMessage(Message):
    """Concrete Message used by the service adapter."""

    __slots__ = ("_role", "_content")

    def __init__(self, role: str, content: str) -> None:
        self._role = role
        self._content = content

    @property
    def role(self) -> str:
        return self._role

    @property
    def content(self) -> str:
        return self._content


class ServiceClaudeChat(Client):
    """Thin wrapper around the autogenerated HTTP client for ai_chat_service."""

    def __init__(self, *, base_url: str, session_token: str, client: GeneratedClient | None = None) -> None:  # type: ignore[name-defined]
        """Create a client that talks to the generated service SDK.

        Args:
            base_url: Base URL of the deployed ai_chat_service (e.g., http://localhost:8000).
            session_token: JWT set by the service's OAuth flow; sent as a cookie for auth.
            client: Optionally provide a preconfigured generated Client instance.

        """
        if GeneratedClient is None:
            raise RuntimeError("Generated client not found. Generate it first from docs/ai_chat_service_openapi.json.")

        self._client = client or GeneratedClient(base_url=base_url)  # type: ignore[call-arg]
        # Ensure our session cookie is set for protected endpoint access
        self._client = self._client.with_cookies({"session_token": session_token})

    def send_message(self, prompt: str, user_id: str) -> Message:  # noqa: ARG002 - user_id used by impl contract
        """Send a prompt to the service and return the assistant's reply.

        The service uses cookie-based auth to identify the user; the provided
        `user_id` is part of the abstract API contract but is not transmitted over the wire.
        """
        # Prefer calling the autogenerated operation function if present
        can_use_generated_op = (
            _OP_FUNC is not None
            and _GenChatRequest is not None
            and hasattr(self._client, "get_httpx_client")
            and hasattr(self._client.get_httpx_client(), "request")
        )
        if can_use_generated_op:  # pragma: no cover - exercised when generated op exists
            result = _OP_FUNC(client=self._client, body=_GenChatRequest(prompt=prompt))
            # Result is expected to be a dict-like or model with `content`
            content = getattr(result, "content", None) or (result.get("content") if isinstance(result, dict) else None)
            if content is None:
                raise RuntimeError("Service returned an unexpected payload without 'content'.")
            return _AdapterMessage(role="assistant", content=str(content))

        # Fallback: use the low-level httpx client
        httpx_client: httpx.Client = self._client.get_httpx_client()
        resp = httpx_client.post("/chat", json={"prompt": prompt})
        if resp.status_code == 200:
            data = resp.json()
            content = data.get("content") if isinstance(data, dict) else None
            if content is None:
                raise RuntimeError("Service returned an unexpected payload without 'content'.")
            return _AdapterMessage(role="assistant", content=str(content))

        if resp.status_code == 401:
            raise PermissionError("Unauthorized: missing or invalid session cookie.")
        raise RuntimeError(f"Service error: HTTP {resp.status_code} - {resp.text}")
