"""Service-backed implementation of the mail client contract."""

from collections.abc import Iterator

import mail_client_api
from mail_client_adapter.message_adapter import ServiceMessage
from mail_client_service_client.fast_api_client import client as generated_client
from mail_client_service_client.fast_api_client.api.default import (
    delete_message_messages_message_id_delete,
    get_message_messages_message_id_get,
    list_messages_messages_get,
    mark_as_read_messages_message_id_mark_as_read_post,
)
from mail_client_service_client.fast_api_client.models.message_summary import MessageSummary
from mail_client_service_client.fast_api_client.models.operation_response import OperationResponse


class ServiceMailClient(mail_client_api.Client):
    """Thin wrapper around the autogenerated HTTP client."""

    def __init__(self, *, base_url: str) -> None:
        """Create a client that talks to the generated service SDK."""
        self._client = generated_client.Client(base_url=base_url)

    def get_message(self, message_id: str) -> mail_client_api.Message:
        """Return the detailed message for the given identifier."""
        result = get_message_messages_message_id_get.sync(client=self._client, message_id=message_id)
        return ServiceMessage(result)

    def get_messages(self, max_results: int = 10) -> Iterator[mail_client_api.Message]:
        """Iterate over fully detailed messages up to the requested maximum."""
        result = list_messages_messages_get.sync(client=self._client, max_results=max_results)
        for summary in result:
            if isinstance(summary, MessageSummary):
                yield self.get_message(summary.id)

    def delete_message(self, message_id: str) -> bool:
        """Delete a message and return True when the service reports success."""
        result = delete_message_messages_message_id_delete.sync(client=self._client, message_id=message_id)
        return isinstance(result, OperationResponse) and bool(result.success)

    def mark_as_read(self, message_id: str) -> bool:
        """Mark a message as read and return True when the service reports success."""
        result = mark_as_read_messages_message_id_mark_as_read_post.sync(client=self._client, message_id=message_id)
        return isinstance(result, OperationResponse) and bool(result.success)
