"""Service-backed implementation of the mail client contract."""

from collections.abc import Iterator

import mail_client_api
from mail_client_service_client.fast_api_client import client as generated_client
from mail_client_service_client.fast_api_client.api.default import (
    delete_message_messages_message_id_delete,
    get_message_messages_message_id_get,
    list_messages_messages_get,
    mark_as_read_messages_message_id_mark_as_read_post,
)

from .message_adapter import ServiceMessage


class ServiceMailClient(mail_client_api.Client):
    """Thin wrapper around the autogenerated HTTP client."""

    def __init__(self, *, base_url: str) -> None:
        """Instantiate the adapter with the remote service base URL."""
        self._client = generated_client.Client(base_url=base_url)

    def get_message(self, message_id: str) -> mail_client_api.Message:
        """Fetch a single message by ID from the service."""
        result = get_message_messages_message_id_get.sync(client=self._client, message_id=message_id)
        return ServiceMessage(result)
    
    def get_messages(self, max_results: int = 10) -> Iterator[mail_client_api.Message]:
        """Yield messages from the service, resolving each to the full payload."""
        summaries = list_messages_messages_get.sync(client=self._client, max_results=max_results)
        for summary in summaries:
            yield self.get_message(summary.additional_properties["id"])

    def delete_message(self, message_id: str) -> bool:
        """Request message deletion; return True when the service reports success."""
        result = delete_message_messages_message_id_delete.sync(client=self._client, message_id=message_id)
        return result.additional_properties["status"] == "deleted"

    def mark_as_read(self, message_id: str) -> bool:
        """Mark a message as read; return True when the service reports success."""
        result = mark_as_read_messages_message_id_mark_as_read_post.sync(client=self._client, message_id=message_id)
        return result.additional_properties["status"] == "read"

